Specify which class to use for unserialization.
SocialiteProviders/Manager pull request #186
Opened 2021-04-03 16:42 UTC by lucasmichot

Specify which class to use for unserialization.

Event though, at some point I would prefer another approach.

2021-04-04 02:41 UTC, atymic requested changes

2021-04-04 02:41 UTC, atymic commented on src/OAuth1/AbstractProvider.php
> +        $temp = unserialize($this->request->session()->get('oauth_temp'), TemporaryCredentials::class);
Pretty sure this should be:
```suggestion
        $temp = unserialize($this->request->session()->get('oauth_temp'), ['allowed_classes' => [TemporaryCredentials::class]]);
```


https://www.php.net/manual/en/function.unserialize.php

2021-04-04 07:09 UTC, lucasmichot commented
Updated @atymic

2021-04-05 01:52 UTC, atymic approved these changes

2021-04-05 01:52 UTC, merged